sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!--", "-->"]

exclude: ['LICENSE','README.txt']

defaults:
  - scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
  - scope:
    path: ""
  values:
    layout: "default"